import time
print("Hello world!")
time.sleep(2)


print("#Hello world!")
time.sleep(1)
print("Hello #world!")
time.sleep(2)
print("#Hello #world!")
time.sleep(2)
print("Hello world!")
time.sleep(1)
print("Hello world!")
time.sleep(1)
print("Hello world!")
time.sleep(1)
print("\Hello \world!")
time.sleep(1)
print("#Hello #world!")
time.sleep(3)
print("Please enter your IP and port like this: IP:port, ex: 128.478.1.4:28463; as #input")
print("[Console] Hello!; as signal to #input")