print("Hello World!")
time.sleep(3)
print(", ".join(['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!', ' ', 'a', 's', ' ', 'l', 'i', 's', 't']))
time.sleep(5)
print("\n".join(['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!', ' ', 'a', 's', ' ', 'w', 'h', 'i', 't', 'e', 's', 'p', 'a', 'c', 'e', 'd', ' ', 'l', 'i', 's']))